apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bsee-pvc
  namespace: postgres  # Ensure this matches your deployment namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard  # This matches your available storage class

