apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kebabcase-release-name" . }}-enterprise-server-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: enterprise-server
    app.kubernetes.io/component: server
{{ include "recommended-labels" . | indent 4 }}
data:
  BSEE_HTTPS_KEYSTORE_PASSWORD: {{ randAlphaNum 20 | b64enc }}
{{- if .Values.database.enterpriseServerUsername }}
  BSEE_ADMIN_REPOSITORY_USERNAME: {{ .Values.database.enterpriseServerUsername | b64enc }}
{{- end -}}
{{- if .Values.database.enterpriseServerConnectionUsername }}
  BSEE_ADMIN_REPOSITORY_CONNECTION_USERNAME: {{ .Values.database.enterpriseServerConnectionUsername | b64enc }}
{{- end -}}
{{- if .Values.database.enterpriseServerPassword }}
  BSEE_ADMIN_REPOSITORY_PASSWORD: {{ .Values.database.enterpriseServerPassword | b64enc }}
{{- end -}}
{{- if .Values.database.scanningResourceUsername }}
  BSEE_AGENT_REPOSITORY_USERNAME: {{ .Values.database.scanningResourceUsername | b64enc }}
{{- end -}}
{{- if .Values.database.scanningResourceConnectionUsername }}
  BSEE_AGENT_REPOSITORY_CONNECTION_USERNAME: {{ .Values.database.scanningResourceConnectionUsername | b64enc }}
{{- end -}}
{{- if .Values.database.scanningResourcePassword }}
  BSEE_AGENT_REPOSITORY_PASSWORD: {{ .Values.database.scanningResourcePassword | b64enc }}
{{- end -}}